name: Build binaries for macOS and Linux, publish Node.js packages, create release

on:
  push:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Package
        run: |
          npm ci
          npm run build
          npm run package:macos

      - name: Create tarball
        run: |
          mv bin/macos/awss awss
          tar -cvzf awss-macos-x64.tar.gz awss

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin-macos
          path: awss-macos-x64.tar.gz

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Package
        run: |
          npm ci
          npm run build
          npm run package:linux

      - name: Create tarball
        run: |
          mv bin/linux/awss awss
          tar -cvzf awss-linux-x64.tar.gz awss

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin-linux
          path: awss-linux-x64.tar.gz

  publish-node-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        continue-on-error: true
        run: |
          npm ci
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup for npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm registry
        continue-on-error: true
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup for GitHub registry
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: debug
        run: cat /home/runner/work/_temp/.npmrc

      - name: login
        run: npm login --registry=https://npm.pkg.github.com

      - name: Publish to GitHub registry
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: [build-macos, build-linux, publish-node-packages]

    runs-on: ubuntu-latest

    steps:
      - name: Download macos tarball
        uses: actions/download-artifact@v3
        with:
          name: bin-macos

      - name: Download linux tarball
        uses: actions/download-artifact@v3
        with:
          name: bin-linux

      - name: Compute checksums
        run: |
          sha256sum awss-macos-x64.tar.gz >> checksums.md
          sha256sum awss-linux-x64.tar.gz >> checksums.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: checksums.md
          files: |
            LICENSE
            awss-macos-x64.tar.gz
            awss-linux-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
